#!/bin/bash

build() {
	add_binary /usr/local/bin/nvme-ata-security
	add_module nvme
	add_full_dir /lib/modules/4.6.2-1-ARCH/extra
	add_full_dir /lib/modules/4.6.2-1-ARCH/kernel/drivers/nvme/host
	add_runscript nvme-ata-security
}

help() {
	echo nvme-ata-security
}
