#!/usr/bin/ash

run_hook() {
	for dev in /dev/nvme*n[0-9]; do
		if nvme-ata-security query $dev 2>&1 |grep -q 'locked: true'; then
			reset
			echo Unlocking $dev
			nvme-ata-security unlock -u $dev -t 3
		fi
	done
}
